import polyglot

dnames={
"01":  "AIN",
"02":  "AISNE",
"03":  "ALLIER",
"05":  "HAUTES-ALPES",
"04":  "ALPES-DE-HAUTE-PROVENCE",
"06":  "ALPES-MARITIMES",
"07":  "ARDÈCHE",
"08":  "ARDENNES",
"09":  "ARIÈGE",
"10":  "AUBE",
"11":  "AUDE",
"12":  "AVEYRON",
"13":  "BOUCHES-DU-RHÔNE",
"14":  "CALVADOS",
"15":  "CANTAL",
"16":  "CHARENTE",
"17":  "CHARENTE-MARITIME",
"18":  "CHER",
"19":  "CORRÈZE",
"2a":  "CORSE-DU-SUD",
"2b":  "HAUTE-CORSE",
"21":  "CÔTE-D'OR",
"22":  "CÔTES-D'ARMOR",
"23":  "CREUSE",
"24":  "DORDOGNE",
"25":  "DOUBS",
"26":  "DRÔME",
"27":  "EURE",
"28":  "EURE-ET-LOIR",
"29":  "FINISTÈRE",
"30":  "GARD",
"31":  "HAUTE-GARONNE",
"32":  "GERS",
"33":  "GIRONDE",
"34":  "HÉRAULT",
"35":  "ILE-ET-VILAINE",
"36":  "INDRE",
"37":  "INDRE-ET-LOIRE",
"38":  "ISÈRE",
"39":  "JURA",
"40":  "LANDES",
"41":  "LOIR-ET-CHER",
"42":  "LOIRE",
"43":  "HAUTE-LOIRE",
"44":  "LOIRE-ATLANTIQUE",
"45":  "LOIRET",
"46":  "LOT",
"47":  "LOT-ET-GARONNE",
"48":  "LOZÈRE",
"49":  "MAINE-ET-LOIRE",
"50":  "MANCHE",
"51":  "MARNE",
"52":  "HAUTE-MARNE",
"53":  "MAYENNE",
"54":  "MEURTHE-ET-MOSELLE",
"55":  "MEUSE",
"56":  "MORBIHAN",
"57":  "MOSELLE",
"58":  "NIÈVRE",
"59":  "NORD",
"60":  "OISE",
"61":  "ORNE",
"62":  "PAS-DE-CALAIS",
"63":  "PUY-DE-DÔME",
"64":  "PYRÉNÉES-ATLANTIQUES",
"65":  "HAUTES-PYRÉNÉES",
"66":  "PYRÉNÉES-ORIENTALES",
"67":  "BAS-RHIN",
"68":  "HAUT-RHIN",
"69":  "RHÔNE",
"70":  "HAUTE-SAÔNE",
"71":  "SAÔNE-ET-LOIRE",
"72":  "SARTHE",
"73":  "SAVOIE",
"74":  "HAUTE-SAVOIE",
"75":  "PARIS",
"76":  "SEINE-MARITIME",
"77":  "SEINE-ET-MARNE",
"78":  "YVELINES",
"79":  "DEUX-SÈVRES",
"80":  "SOMME",
"81":  "TARN",
"82":  "TARN-ET-GARONNE",
"83":  "VAR",
"84":  "VAUCLUSE",
"85":  "VENDÉE",
"86":  "VIENNE",
"87":  "HAUTE-VIENNE",
"88":  "VOSGES",
"89":  "YONNE",
"90":  "TERRITOIRE DE BELFORT",
"91":  "ESSONNE",
"92":  "HAUTS-DE-SEINE",
"93":  "SEINE-SAINT-DENIS",
"94":  "VAL-DE-MARNE",
"95":  "VAL-D'OISE",
"976":  "MAYOTTE",
"971":  "GUADELOUPE",
"973":  "GUYANE",
"972":  "MARTINIQUE",
"974":  "RÉUNION"
}

@polyglot.export_value
def getDepartmentNameById(deptId):
  if deptId in dnames:
      return dnames[deptId]
  else: 
    return "-"
    


